import { StyleSheet, Dimensions } from "react-native";

export const styles = StyleSheet.create({
    container: {
      alignItems: 'center',
      justifyContent: 'center',
      flex: 1,
      backgroundColor: '#5c635e',
    },
    inputValues: {
      height: 50,
      flex: 1,
      padding: 10,
      marginLeft: 20,
      color: '#fff',
      fontFamily: 'ArialRoundedMTBold',
      fontSize: 16,
    },
    inputContainer: {
      flexDirection: 'column',
      alignContent: 'center',
      justifyContent: 'center',
      position: 'relative',
      width: Dimensions.get('window').width - 25,
      height: 730,
      borderStyle: 'solid',
      borderWidth: 1,
      borderColor: '#31c48d',
      marginTop: '10%',
      borderRadius: 50,
    },
    inputView: {
      backgroundColor: '#31c48d',
      borderRadius: 30,
      width: '50%',
      height: 45,
      marginBottom: 20,
      marginTop: 5,
      alignItems: 'center',
      justifyContent: 'center',
      paddingRight: '5%',
      bottom: 15,
      position: 'relative',
    },
    inputDescription: {
      fontFamily: 'ArialRoundedMTBold',
      color: '#31c48d',
      fontSize: 18,
      bottom: '7%',
      paddingRight: 15,
    },
    inputIndivContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      alignSelf: 'flex-start',
      position: 'relative',
      left: 5,
      marginTop: 50,
    },
    titleContainer: {
      alignItems: 'center',
      justifyContent: 'center',
      flexDirection: 'row',
      backgroundColor: '#5c635e',
      opacity: 0.75,
      width: Dimensions.get('window').width + 20,
      height: 60,
      top: 25,
      borderStyle: 'solid',
      borderWidth: 1,
      borderTopColor: '#5c635e',
      borderBottomColor: 'rgba(49, 196, 141, 0.55)',
    },
    titleTextContainer: {
      position: 'relative',
      paddingRight: 55,
      paddingLeft: 35,
    },
    titleText: {
      color: '#31c48d',
      fontSize: 20,
      fontWeight: 'bold',
      fontFamily: 'ArialRoundedMTBold',
      right: 5,
    },
    profileBttn: {
      width: 45,
      height: 45,
      backgroundColor: '#31c48d',
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: 45 / 2,
      position: 'relative',
      borderStyle: 'solid',
      borderWidth: 1,
      borderColor: '#fff',
    },
    logoContainer: {
      position: 'relative',
      paddingRight: 35,
    },
    logoStyle: {
      width: 45,
      height: 45,
      borderRadius: 45 / 2,
    },
    descriptionContainer: {
      alignItems: 'center',
      justifyContent: 'center',
      flexDirection: 'column',
      flex: 1,
      bottom: '5%',
    },
    descriptionInput: {
      backgroundColor: '#fff',
      width: 250,
      height: 150,
      padding: 5,
      borderRadius: 10,
    },
    descriptionText: {
      fontFamily: 'ArialRoundedMTBold',
      color: '#31c48d',
      fontSize: 18,
      paddingRight: 15,
    },
    descriptionView: {
      backgroundColor: '#31c48d',
      borderRadius: 30,
      width: '80%',
      height: 200,
      marginBottom: 20,
      marginTop: 20,
      alignItems: 'center',
      justifyContent: 'center',
      position: 'relative',
    },
    addExpenseBttn: {
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: '#31c48d',
      width: 150,
      height: 50,
      borderRadius: 150 / 2,
      position: 'relative',
      top: '10%',
    },
    expenseBttnText: {
      color: '#fff',
      fontFamily: 'ArialRoundedMTBold',
      fontSize: 16,
    },
  });